version:  '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog

  phpmyadmin:
    # depends_on:
    #   - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './apps/blog/public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/blog/:/usr/src/app'
    restart: on-failure
    user: 1000:1000